---
homebrew_installed_packages:
  - yt-dlp

homebrew_cask_apps:
  - audio-hijack
  - brave-browser
  - discord
  - fission
  - fl-studio
  - imazing
  - loopback
  - microsoft-teams
  - skype
  - slack
  - wirecast
  - zoom

dockitems_remove:
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Freeform
  - TV
  - Music
  - News
  - App Store

dockitems_persist:
  - name: "Launchpad"
    path: "/System/Applications/Launchpad.app/"
    pos: 1

  - name: "Mission Control"
    path: "/System/Applications/Mission Control.app/"
    pos: 2

  - name: "System Settings"
    path: "/System/Applications/System Settings.app/"
    pos: 3

  - name: "Brave Browser"
    path: "/Applications/Brave Browser.app/"
    pos: 4

  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"
    pos: 5

  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 6

  - name: "Calculator"
    path: "/System/Applications/Calculator.app/"
    pos: 7
